USE MASTER
GO
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE Name = 'SONUNGVIEN')
BEGIN
	DROP DATABASE SONUNGVIEN
END
GO
CREATE DATABASE SONUNGVIEN
GO
USE SONUNGVIEN
GO
CREATE TABLE Category
( 
	CategoryID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CategoryName NVARCHAR NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	[Image] VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
);
CREATE TABLE Product
(
	ProductID INT NOT NULL IDENTITY (1,1),
	ProductName NVARCHAR NOT NULL,
	ProductDescription NVARCHAR NOT NULL,
	ProductSold INT NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

	CategoryID INT NOT NULL,
	PRIMARY KEY (ProductID),
	FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
)

CREATE TABLE Discount
(
	DiscountID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	DiscountName NVARCHAR NOT NULL,
	DiscountCalUnit NVARCHAR NOT NULL,
	DiscountCondition INT NOT NULL,
	DiscountMaxValue INT NOT NULL,
	DiscountRemark NVARCHAR NOT NULL,
	DiscountAvailableFrom DATETIME NOT NULL,
	DiscountAvailableUntil DATETIME NOT NULL,
	DiscountValue INT NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	[Image] VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
);

CREATE TABLE DetailedProduct
(
	DetailedProductID INT NOT NULL IDENTITY (1,1),
	DetailedProductPRICE INT NOT NULL,
	DetailedProductQUANTITY INT NOT NULL,
	DetailedProductName CHAR NOT NULL,
	ProductID INT NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	[Image] VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

	PRIMARY KEY (DetailedProductID),
	FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);

CREATE TABLE BillStatus
(
	BillStatusID INT NOT NULL IDENTITY (1,1),
	BillStatusName INT NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

	PRIMARY KEY (BillStatusID)
);

CREATE TABLE TermOfPayment
(
	PaymentID INT NOT NULL IDENTITY (1,1),
	PaymentName NVARCHAR NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	[Image] VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

	PRIMARY KEY (PaymentID)
);

CREATE TABLE Bill
(
	BillID INT NOT NULL IDENTITY (1,1),
	BillPhoneNumber NVARCHAR NOT NULL,
	BillLastName NVARCHAR NOT NULL,
	BillNote NVARCHAR NOT NULL,
	BillFirstName NVARCHAR NOT NULL,
	BillPostcode NVARCHAR NOT NULL,
	BillEmail NVARCHAR NOT NULL,
	BillProvince NVARCHAR NOT NULL,
	BillWard NVARCHAR NOT NULL,
	BillAddress NVARCHAR NOT NULL,
	BillPrice INT NOT NULL,
	BillOldPrice INT NOT NULL,
	BillTaxAmount INT NOT NULL,
	BillUpdatedAt DATETIME NOT NULL,
	BillCreatedAt DATETIME NOT NULL,
	BillSequenceNumber INT NOT NULL,
	BillFinalPrice INT NOT NULL,
	BillDiscountAmount INT NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

	BillTermOfPayment INT NOT NULL,
	BillStatus INT NOT NULL,
	PRIMARY KEY (BillID),
	FOREIGN KEY (BillStatus) REFERENCES BillStatus(BillStatusID),
	FOREIGN KEY (BillTermOfPayment) REFERENCES TermOfPayment(PaymentID)
);

CREATE TABLE BillProduct
(
	BillID INT NOT NULL IDENTITY (1,1),
	DetailedProductID INT NOT NULL,
	Amount INT NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

	PRIMARY KEY (BillID, DetailedProductID),
	FOREIGN KEY (BillID) REFERENCES Bill(BillID),
	FOREIGN KEY (DetailedProductID) REFERENCES DetailedProduct(DetailedProductID)
);

CREATE TABLE DiscountUse
(
	DiscountID INT NOT NULL,
	BillID INT NOT NULL,
	UsedAt DATETIME NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

	PRIMARY KEY (DiscountID, BillID),
	FOREIGN KEY (DiscountID) REFERENCES Discount(DiscountID),
	FOREIGN KEY (BillID) REFERENCES Bill(BillID)
);
CREATE TABLE Menu
(
    MenuID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    MenuName NVARCHAR NOT NULL,
    [Order] INT,
    Meta VARCHAR,
    [Image] VARCHAR,
    Hide BIT,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL
);

CREATE TABLE Logo
(
	LogoID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	LogoName NVARCHAR NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	[Image] VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
);

CREATE TABLE Footer
( 
	FooterID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	FooterName NVARCHAR NOT NULL,
	FooterDescription NVARCHAR NOT NULL,

	[Order] INT,
	Meta VARCHAR,
	[Image] VARCHAR,
	Hide BIT,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
);

CREATE TABLE Banner
(
    BannerID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    BannerName NVARCHAR NOT NULL,
    BannerMessage NVARCHAR NOT NULL,
    BannerDescription NVARCHAR NOT NULL,
    [Order] INT,
    Meta VARCHAR,
    [Image] VARCHAR,
    Hide BIT,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL
);

CREATE TABLE ProductImage
(
	ProductImageID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	ProductImageLink VARCHAR,
	ProductID INT NOT NULL,
	FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
)